# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='MIT'

[[mods]]
modId="alchemy"
version="${file.jarVersion}"
displayName="Alchemy"
credits="Forge for creating an amazing loading. KotlinForForge team for letting me use an amazing language with my mod"
authors="ElizabethLFransen, LizIsNotInting"
description='''
A alchemy / tech mod for transmuting one item to another
'''
[[dependencies.alchemy]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alchemy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
